services:
  database:
    image: danielxhogan/movieshlok-database
    container_name: movieshlok-database
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - movieshlok-data:/var/lib/postgresql/data

  cache:
    image: redis
    container_name: movieshlok-cache
    ports:
      - 6379:6379

  backend:
    image: danielxhogan/movieshlok-backend
    container_name: movieshlok-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      TMDB_BASE_URL: ${TMDB_BASE_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
    network_mode: host

  frontend:
    image: danielxhogan/movieshlok-frontend
    container_name: movieshlok-frontend
    ports:
      - ${FRONTEND_PORT}:3000

volumes:
  movieshlok-data:
