services:
  database:
    image: danielxhogan/movieshlok-database
    container_name: movieshlok-database
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - movieshlok-data:/var/lib/postgresql/data

  # backend:
  #   image: danielxhogan/movieshlok-backend
  #   container_name: movieshlok-backend
  #   ports:
  #     - ${BACKEND_PORT}:3030
  #   environment:
  #     DATABASE_URL: ${DATABASE_URL}

  frontend:
    image: danielxhogan/movieshlok-frontend
    container_name: movieshlok-frontend
    ports:
      - ${FRONTEND_PORT}:3000
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_HOST: ${BACKEND_HOST}



volumes:
  movieshlok-data: