import { api } from "@/api/server";
import HelloClient from "@/components/HelloClient";
import HelloServer from "@/components/HelloServer";
import HelloDB from "@/components/HelloDB";
import Head from "next/head";
import Link from "next/link";

export default async function Home() {
  const hello = await api.example.hello({ text: "from the server" });
  const dbData = await api.example.getAll();
  console.log(`DBDATA::::::{ ${dbData} }`);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HelloClient />
        <HelloServer data={hello} />
        <HelloDB data={dbData} />
        <div>
          <Link href="/test1">test 1</Link>
        </div>
        <div>
          <Link href="/test2">test 2</Link>
        </div>
        <div>
          <Link href="/test3">test 3</Link>
        </div>
      </main>
    </>
  );
}
